/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Appearance: typeof import('./src/components/settings/appearance.vue')['default']
    AppMenu: typeof import('./src/components/header/AppMenu.vue')['default']
    BottomBar: typeof import('./src/components/bottombar/BottomBar.vue')['default']
    BottomBarButton: typeof import('./src/components/bottombar/BottomBarButton.vue')['default']
    CodeMirrorEditor: typeof import('./src/components/editor/markdown/codemirror/CodeMirrorEditor.vue')['default']
    DragDropIndicator: typeof import('./src/components/DragDropIndicator.vue')['default']
    EditorTab: typeof import('./src/components/settings/EditorTab.vue')['default']
    EditorWrap: typeof import('./src/components/editor/markdown/EditorWrap.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSplitter: typeof import('element-plus/es')['ElSplitter']
    ElSplitterPanel: typeof import('element-plus/es')['ElSplitterPanel']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElText: typeof import('element-plus/es')['ElText']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTree: typeof import('element-plus/es')['ElTree']
    FileProperties: typeof import('./src/components/sidebar/filetree/FileProperties.vue')['default']
    FileTab: typeof import('./src/components/settings/FileTab.vue')['default']
    FileTree: typeof import('./src/components/sidebar/filetree/FileTree.vue')['default']
    FileTreeMenu: typeof import('./src/components/sidebar/filetree/FileTreeMenu.vue')['default']
    GeneralTab: typeof import('./src/components/settings/GeneralTab.vue')['default']
    HeaderMenu: typeof import('./src/components/HeaderMenu.vue')['default']
    ImageViewer: typeof import('./src/components/editor/image/ImageViewer.vue')['default']
    MainArea: typeof import('./src/components/MainArea.vue')['default']
    MarkdownPreview: typeof import('./src/components/common/markdown/MarkdownPreview.vue')['default']
    MarkdownTab: typeof import('./src/components/settings/MarkdownTab.vue')['default']
    MenuItem: typeof import('./src/components/header/MenuItem.vue')['default']
    MilkdownEditor: typeof import('./src/components/editor/markdown/milkdown/MilkdownEditor.vue')['default']
    Outline: typeof import('./src/components/sidebar/outline/Outline.vue')['default']
    PdfViewer: typeof import('./src/components/editor/pdf/PdfViewer.vue')['default']
    SearchReplace: typeof import('./src/components/editor/markdown/plugins/find/SearchReplace.vue')['default']
    Settings: typeof import('./src/components/settings/index.vue')['default']
    SettingsModal: typeof import('./src/components/header/SettingsModal.vue')['default']
    SidePanel: typeof import('./src/components/SidePanel.vue')['default']
    SidePanelHeader: typeof import('./src/components/sidebar/SidePanelHeader.vue')['default']
    SubMenu: typeof import('./src/components/header/SubMenu.vue')['default']
    TableSelector: typeof import('./src/components/editor/markdown/plugins/table/TableSelector.vue')['default']
    UpdateTab: typeof import('./src/components/settings/UpdateTab.vue')['default']
    VersionCompare: typeof import('./src/components/sidebar/version/VersionCompare.vue')['default']
    VersionHistory: typeof import('./src/components/sidebar/version/VersionHistory.vue')['default']
    VersionMenu: typeof import('./src/components/sidebar/version/VersionMenu.vue')['default']
    WebdavAccountForm: typeof import('./src/components/settings/webdav/WebdavAccountForm.vue')['default']
    WebDAVTab: typeof import('./src/components/settings/WebDAVTab.vue')['default']
    WelcomePanel: typeof import('./src/components/editor/welcome/WelcomePanel.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
